### ISSUE TITLE
Modular Exponentiation compilation error.

### ISSUE THREAD

**Issue by aashutoshrathi** [NAU-ACM/ACM-ICPC-Preparation#2]
[modular-exponent.cpp](https://github.com/NAU-ACM/ACM-ICPC-Preparation/blob/master/Week1/Modular-Exponentiation/modular-exponent.cpp) will not work without 
```cpp
using namespace std;
```
- [x] Assign this to me.

**Comment by BedirT** [comment]
Thanks
